import colorama
from colorama import Fore
import textwrap
import json
from groq import Groq  # Correct import

# Initialize colorama for colorful output
colorama.init(autoreset=True)

# Set your API key
api_key = "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"

# Initialize Groq client with the API key
client = Groq(api_key=api_key)

def load_system_message(filename):
    """Load system message content from a JSON file."""
        with open(filename, 'r') as file:
                data = json.load(file)
                        return data.get("content", "")

                        def format_response(assistant_reply):
                            """Format the assistant's reply with borders and text wrapping."""
                                width = 60  # Fixed width for the inner content (including borders)
                                    wrapped_lines = textwrap.fill(assistant_reply, width=width - 10).split('\n')  # Wrap text with adjusted width
                                        
                                            # Build the top and bottom borders of the box with new characters
                                                top_border = f"{Fore.GREEN}╔" + "@" * (width) + "╗"  # Changed "=" to "@"
                                                    bottom_border = f"{Fore.GREEN}╚" + "^" * (width) + "╝"  # Changed "=" to "^"
                                                        
                                                            # Build the content inside the box
                                                                content_lines = []
                                                                    for line in wrapped_lines:
                                                                            content_lines.append(f"{Fore.GREEN}║ {line.ljust(width - 2)} ║")  # Padding on both sides
                                                                                
                                                                                    # Combine the parts into a formatted response
                                                                                        return f"{top_border}\n" + "\n".join(content_lines) + f"\n{bottom_border}"

                                                                                        def chat_with_model():
                                                                                            # Load system message from JSON file
                                                                                                system_message_content = load_system_message("instruction.json")
                                                                                                    
                                                                                                        # Set initial system message
                                                                                                            system_message = {
                                                                                                                    "role": "system",
                                                                                                                            "content": system_message_content
                                                                                                                                }
                                                                                                                                    
                                                                                                                                        # Initialize the list of messages for the conversation
                                                                                                                                            conversation = [system_message]
                                                                                                                                                
                                                                                                                                                    print(Fore.CYAN + "Start chatting with the model. Type 'exit' to quit.")
                                                                                                                                                        
                                                                                                                                                            while True:
                                                                                                                                                                    # Get user input from the terminal
                                                                                                                                                                            user_input = input(Fore.YELLOW + "@🧑‍⚖️••• ")  # Changed user prompt
                                                                                                                                                                                    
                                                                                                                                                                                            # Exit condition
                                                                                                                                                                                                    if user_input.lower() in ["exit", "quit"]:
                                                                                                                                                                                                                print(Fore.CYAN + "Exiting chat. Goodbye!")
                                                                                                                                                                                                                            break
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                            # Add user message to the conversation
                                                                                                                                                                                                                                                    conversation.append({
                                                                                                                                                                                                                                                                "role": "user",
                                                                                                                                                                                                                                                                            "content": user_input
                                                                                                                                                                                                                                                                                    })
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                    # Call the Groq API with the conversation messages
                                                                                                                                                                                                                                                                                                            chat_completion = client.chat.completions.create(
                                                                                                                                                                                                                                                                                                                        messages=conversation,
                                                                                                                                                                                                                                                                                                                                    model="llama3-8b-8192",
                                                                                                                                                                                                                                                                                                                                                temperature=0.5,
                                                                                                                                                                                                                                                                                                                                                            max_tokens=1024,
                                                                                                                                                                                                                                                                                                                                                                        top_p=1,
                                                                                                                                                                                                                                                                                                                                                                                    stop=None,
                                                                                                                                                                                                                                                                                                                                                                                                stream=False
                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                        # Extract the assistant's response
                                                                                                                                                                                                                                                                                                                                                                                                                                assistant_reply = chat_completion.choices[0].message.content
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                # Add the assistant's reply to the conversation
                                                                                                                                                                                                                                                                                                                                                                                                                                                        conversation.append({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "role": "assistant",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "content": assistant_reply
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Print the assistant's formatted reply
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(Fore.CYAN + "\n@🤖•••")  # Changed assistant prompt
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(format_response(assistant_reply))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print()  # Blank line for spacing

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Run the chat function
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                chat_with_model()
                                                                                                                                                                                                                